import { useEffect, useState } from "react";
import data from "../data/temporal.json";
import type { TemporalData } from "../lib/types";
import TimeMachine from "./TimeMachine";
import OverMergeGuard from "./OverMergeGuard";

// Generated by `mix run temporal_export.exs` from the real Elixir engine.
const temporal = data as unknown as TemporalData;

type Tab = "real" | "synthetic";

export default function App() {
  const [tab, setTab] = useState<Tab>("real");

  // Deep-link the active scene via #hash (shareable; also lets the initial view be chosen by URL).
  useEffect(() => {
    const fromHash = window.location.hash.replace("#", "");
    if (fromHash === "synthetic" || fromHash === "real") setTab(fromHash);
  }, []);

  const select = (t: Tab) => {
    setTab(t);
    window.history.replaceState(null, "", `#${t}`);
  };

  return (
    <div>
      <div className="tabs" role="tablist" aria-label="scene">
        <button
          className="tab"
          role="tab"
          aria-selected={tab === "real"}
          onClick={() => select("real")}
        >
          ① The time machine — 422156
        </button>
        <button
          className="tab"
          role="tab"
          aria-selected={tab === "synthetic"}
          onClick={() => select("synthetic")}
        >
          ② Over-merge guard
        </button>
      </div>

      {tab === "real" ? (
        <TimeMachine scene={temporal.real} />
      ) : (
        <OverMergeGuard scene={temporal.synthetic} />
      )}
    </div>
  );
}
