import data from "../data/temporal.json";
import type { TemporalData } from "../lib/types";
import TimeMachine from "./TimeMachine";

// Generated by `mix run temporal_export.exs` from the real Elixir engine.
const temporal = data as unknown as TemporalData;

export default function App() {
  return <TimeMachine scene={temporal.real} />;
}
