import data from "../data/temporal.json";
import type { TemporalData } from "../lib/types";
import OverMergeGuard from "./OverMergeGuard";

// Generated by `mix run temporal_export.exs` from the real Elixir engine.
const temporal = data as unknown as TemporalData;

export default function GuardApp() {
  return <OverMergeGuard scene={temporal.synthetic} />;
}
