import { useEffect, useState, type ReactElement } from "react";
import { AnimatePresence, motion } from "motion/react";
import data from "../data/story.json";
import temporalData from "../data/temporal.json";
import type { StoryData } from "../lib/story";
import type { TemporalData } from "../lib/types";
import TimeMachine from "./TimeMachine";
import OverMergeGuard from "./OverMergeGuard";
import { advance, flatIndex, jumpTo, totalSteps, type Position } from "../lib/steps";
import { caption } from "../lib/narration";
import { actionInto } from "../lib/actions";
import OldWay from "./chapters/OldWay";
import ClaimsIntro from "./chapters/ClaimsIntro";
import PriorityDuel from "./chapters/PriorityDuel";
import MistakeArc from "./chapters/MistakeArc";

// Generated by `mix run demo_export.exs` from the real Elixir engine (oldWay excepted — see story.ts).
const story = data as unknown as StoryData;
// Generated by `mix run temporal_export.exs` — chapters 4/5 embed the existing scenes.
const temporal = temporalData as unknown as TemporalData;

interface Chapter {
  id: string;
  title: string;
  stepIds: string[];
  render: (step: number) => ReactElement;
}

const CHAPTERS: Chapter[] = [
  {
    id: "oldWay",
    title: "The old way",
    stepIds: story.oldWay.steps.map((s) => s.id),
    render: (step) => <OldWay scene={story.oldWay} step={step} />,
  },
  {
    id: "claims",
    title: "Claims, not records",
    stepIds: story.claims.steps.map((s) => s.id),
    render: (step) => <ClaimsIntro scene={story.claims} step={step} />,
  },
  {
    id: "priority",
    title: "Who wins?",
    stepIds: story.priority.steps.map((s) => s.id),
    render: (step) => <PriorityDuel scene={story.priority} step={step} />,
  },
  {
    id: "machine",
    title: "Identity has a when",
    stepIds: ["scrub"],
    render: () => <TimeMachine scene={temporal.real} embedded />,
  },
  {
    id: "guard",
    title: "The guard",
    stepIds: ["bridge"],
    render: () => <OverMergeGuard scene={temporal.synthetic} embedded />,
  },
  {
    id: "mistake",
    title: "The mistake is cheap",
    stepIds: story.mistake.steps.map((s) => s.id),
    render: (step) => <MistakeArc scene={story.mistake} step={step} />,
  },
];

const COUNTS = CHAPTERS.map((c) => c.stepIds.length);

// Deep-link a position with ?c=<chapter>&s=<step> (1-based) — refresh-safe mid-talk.
function initialPos(): Position {
  if (typeof window === "undefined") return { chapter: 0, step: 0 };
  const q = new URLSearchParams(window.location.search);
  const pos = jumpTo(Number(q.get("c") ?? "1") - 1, COUNTS);
  const step = Number(q.get("s") ?? "1") - 1;
  return { ...pos, step: Math.max(0, Math.min(COUNTS[pos.chapter] - 1, step)) };
}

// The guided story: → / ← (or the edge buttons) advance step by step; 1-6 jump to a chapter.
export default function Story() {
  const [pos, setPos] = useState<Position>(initialPos);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      // leave keys alone inside the time machine's scrubber (or any input)
      if (e.target instanceof HTMLElement && e.target.tagName === "INPUT") return;
      if (e.key === "ArrowRight" || e.key === " ") {
        e.preventDefault();
        setPos((p) => advance(p, 1, COUNTS));
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        setPos((p) => advance(p, -1, COUNTS));
      } else if (/^[1-9]$/.test(e.key)) {
        setPos(jumpTo(Number(e.key) - 1, COUNTS));
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  const chapter = CHAPTERS[pos.chapter];
  const stepId = chapter.stepIds[pos.step];
  const atStart = pos.chapter === 0 && pos.step === 0;
  const atEnd = pos.chapter === CHAPTERS.length - 1 && pos.step === COUNTS[pos.chapter] - 1;

  // The advance button IS the next operation: run the import, or act as the steward.
  const next = advance(pos, 1, COUNTS);
  const action = next.chapter === pos.chapter ? actionInto(chapter.id, chapter.stepIds[next.step]) : undefined;
  const actionLabel = atEnd
    ? "↺ restart the story"
    : (action?.label ?? `next chapter: ${CHAPTERS[next.chapter]?.title}`);
  const actionKind = atEnd ? "watch" : (action?.kind ?? "watch");
  const stewardNeeded = !atEnd && action?.kind === "steward";

  return (
    <div className="story">
      <nav className="story-rail" aria-label="chapters">
        {CHAPTERS.map((c, i) => (
          <button
            key={c.id}
            className={`rail-btn${i === pos.chapter ? " active" : ""}${i < pos.chapter ? " done" : ""}`}
            onClick={() => setPos(jumpTo(i, COUNTS))}
          >
            <span className="rail-num">{i + 1}</span>
            <span className="rail-title">{c.title}</span>
            {i === pos.chapter && c.stepIds.length > 1 && (
              <span className="rail-steps">
                {pos.step + 1}/{c.stepIds.length}
              </span>
            )}
          </button>
        ))}
        <span className="rail-progress">
          {flatIndex(pos, COUNTS) + 1} / {totalSteps(COUNTS)}
        </span>
      </nav>

      <div className="story-stage">
        <AnimatePresence mode="wait">
          <motion.div
            key={chapter.id}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.25 }}
          >
            {chapter.render(pos.step)}
          </motion.div>
        </AnimatePresence>
      </div>

      <AnimatePresence>
        {stewardNeeded && (
          <motion.div
            className="steward-alert"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
          >
            ⚠ the engine has stopped — a <b>steward decision</b> is required to continue
          </motion.div>
        )}
      </AnimatePresence>

      <div className="story-nav">
        <button
          className="nav-btn"
          onClick={() => setPos((p) => advance(p, -1, COUNTS))}
          disabled={atStart}
          aria-label="previous step"
        >
          ←
        </button>
        <AnimatePresence mode="wait">
          <motion.p
            className="story-caption"
            key={`${chapter.id}/${stepId}`}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            {caption(chapter.id, stepId)}
          </motion.p>
        </AnimatePresence>
        <motion.button
          key={actionLabel}
          className={`action-btn ${actionKind}`}
          onClick={() => setPos((p) => (atEnd ? { chapter: 0, step: 0 } : advance(p, 1, COUNTS)))}
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          {actionKind === "import" && <span className="action-icon">▶</span>}
          {actionKind === "steward" && <span className="action-icon">⚠</span>}
          {actionLabel}
        </motion.button>
      </div>
    </div>
  );
}
