import { useEffect, useState, type ReactElement } from "react";
import { AnimatePresence, motion } from "motion/react";
import data from "../data/story.json";
import type { StoryData } from "../lib/story";
import { advance, flatIndex, jumpTo, totalSteps, type Position } from "../lib/steps";
import { caption } from "../lib/narration";
import OldWay from "./chapters/OldWay";
import ClaimsIntro from "./chapters/ClaimsIntro";
import PriorityDuel from "./chapters/PriorityDuel";
import MistakeArc from "./chapters/MistakeArc";

// Generated by `mix run demo_export.exs` from the real Elixir engine (oldWay excepted — see story.ts).
const story = data as unknown as StoryData;

interface Chapter {
  id: string;
  title: string;
  stepIds: string[];
  render: (step: number) => ReactElement;
}

// Placeholder bodies until the chapter components land (gr-7ib) and the existing scenes embed (gr-zfc).
function Placeholder({ title, stepId }: { title: string; stepId: string }) {
  return (
    <div className="panel story-placeholder">
      <div className="readout">
        <b>{title}</b> · step <code>{stepId}</code>
      </div>
      <p className="caption">Chapter component under construction — the data for this step is already exported.</p>
    </div>
  );
}

const CHAPTERS: Chapter[] = [
  {
    id: "oldWay",
    title: "The old way",
    stepIds: story.oldWay.steps.map((s) => s.id),
    render: (step) => <OldWay scene={story.oldWay} step={step} />,
  },
  {
    id: "claims",
    title: "Claims, not records",
    stepIds: story.claims.steps.map((s) => s.id),
    render: (step) => <ClaimsIntro scene={story.claims} step={step} />,
  },
  {
    id: "priority",
    title: "Who wins?",
    stepIds: story.priority.steps.map((s) => s.id),
    render: (step) => <PriorityDuel scene={story.priority} step={step} />,
  },
  {
    id: "machine",
    title: "Identity has a when",
    stepIds: ["scrub"],
    render: () => <Placeholder title="Identity has a when" stepId="scrub" />,
  },
  {
    id: "guard",
    title: "The guard",
    stepIds: ["bridge"],
    render: () => <Placeholder title="The guard" stepId="bridge" />,
  },
  {
    id: "mistake",
    title: "The mistake is cheap",
    stepIds: story.mistake.steps.map((s) => s.id),
    render: (step) => <MistakeArc scene={story.mistake} step={step} />,
  },
];

const COUNTS = CHAPTERS.map((c) => c.stepIds.length);

// The guided story: → / ← (or the edge buttons) advance step by step; 1-6 jump to a chapter.
export default function Story() {
  const [pos, setPos] = useState<Position>({ chapter: 0, step: 0 });

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      // leave keys alone inside the time machine's scrubber (or any input)
      if (e.target instanceof HTMLElement && e.target.tagName === "INPUT") return;
      if (e.key === "ArrowRight" || e.key === " ") {
        e.preventDefault();
        setPos((p) => advance(p, 1, COUNTS));
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        setPos((p) => advance(p, -1, COUNTS));
      } else if (/^[1-9]$/.test(e.key)) {
        setPos(jumpTo(Number(e.key) - 1, COUNTS));
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  const chapter = CHAPTERS[pos.chapter];
  const stepId = chapter.stepIds[pos.step];
  const atStart = pos.chapter === 0 && pos.step === 0;
  const atEnd = pos.chapter === CHAPTERS.length - 1 && pos.step === COUNTS[pos.chapter] - 1;

  return (
    <div className="story">
      <nav className="story-rail" aria-label="chapters">
        {CHAPTERS.map((c, i) => (
          <button
            key={c.id}
            className={`rail-btn${i === pos.chapter ? " active" : ""}${i < pos.chapter ? " done" : ""}`}
            onClick={() => setPos(jumpTo(i, COUNTS))}
          >
            <span className="rail-num">{i + 1}</span>
            <span className="rail-title">{c.title}</span>
            {i === pos.chapter && c.stepIds.length > 1 && (
              <span className="rail-steps">
                {pos.step + 1}/{c.stepIds.length}
              </span>
            )}
          </button>
        ))}
        <span className="rail-progress">
          {flatIndex(pos, COUNTS) + 1} / {totalSteps(COUNTS)}
        </span>
      </nav>

      <div className="story-stage">
        <AnimatePresence mode="wait">
          <motion.div
            key={chapter.id}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.25 }}
          >
            {chapter.render(pos.step)}
          </motion.div>
        </AnimatePresence>
      </div>

      <div className="story-nav">
        <button
          className="nav-btn"
          onClick={() => setPos((p) => advance(p, -1, COUNTS))}
          disabled={atStart}
          aria-label="previous step"
        >
          ←
        </button>
        <AnimatePresence mode="wait">
          <motion.p
            className="story-caption"
            key={`${chapter.id}/${stepId}`}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            {caption(chapter.id, stepId)}
          </motion.p>
        </AnimatePresence>
        <button
          className="nav-btn"
          onClick={() => setPos((p) => advance(p, 1, COUNTS))}
          disabled={atEnd}
          aria-label="next step"
        >
          →
        </button>
      </div>
    </div>
  );
}
